export const ROLES = {
  ADMIN: "Admin",
  GENERAL: "General",
  ODECA: "Cafe_ODECA",
  RESPONSABLE: "Cafe_Responsable",
  SOCIETE: "Cafe_Chef_societe",
  SUPERVISEUR_REGIONAL: "Superviseur_Regional",
  SUPERVISEUR: "Superviseur",
};

export const ROUTE_PERMISSIONS = {
  "/odeca-dashboard/collectors": [ROLES.ADMIN],
  "/odeca-dashboard/societies": [ROLES.ADMIN, ROLES.GENERAL, ROLES.ODECA,ROLES.SUPERVISEUR],
  "/odeca-dashboard/payments": [
    ROLES.ADMIN,
    ROLES.GENERAL,
    ROLES.ODECA,
    ROLES.SOCIETE,
    ROLES.SUPERVISEUR_REGIONAL,
    ROLES.SUPERVISEUR,
  ],
  "/odeca-dashboard/home": [
    ROLES.ADMIN,
    ROLES.GENERAL,
    ROLES.ODECA,
    ROLES.SOCIETE,
    ROLES.SUPERVISEUR_REGIONAL,
    ROLES.SUPERVISEUR,
  ],

  "/odeca-dashboard/cultivators": [
    ROLES.ADMIN,
    ROLES.GENERAL,
    ROLES.ODECA,
    ROLES.SOCIETE,
    ROLES.SUPERVISEUR_REGIONAL,
    ROLES.SUPERVISEUR,
  ],
  "/odeca-dashboard/ct": [
    ROLES.ADMIN,
    ROLES.GENERAL,
    ROLES.ODECA,
    ROLES.SOCIETE,
    ROLES.SUPERVISEUR_REGIONAL,
    ROLES.SUPERVISEUR,
  ],
  "/odeca-dashboard/usine": [ROLES.ADMIN, ROLES.GENERAL, ROLES.ODECA,ROLES.SUPERVISEUR],
  "/odeca-dashboard/stocks": [
    ROLES.ADMIN,
    ROLES.GENERAL,
    ROLES.ODECA,
    ROLES.SOCIETE,
    ROLES.SUPERVISEUR_REGIONAL,
    ROLES.SUPERVISEUR,
  ],
  "/odeca-dashboard/stocks/achats": [
    ROLES.ADMIN,
    ROLES.GENERAL,
    ROLES.ODECA,
    ROLES.SOCIETE,
    ROLES.SUPERVISEUR_REGIONAL,
    ROLES.SUPERVISEUR,
  ],

  "/odeca-dashboard/stocks/transfers": [
    ROLES.ADMIN,
    ROLES.GENERAL,
    ROLES.ODECA,
    ROLES.SOCIETE,
    ROLES.SUPERVISEUR_REGIONAL,
    ROLES.SUPERVISEUR,
  ],
  "/odeca-dashboard/maps": [
    ROLES.ADMIN,
    ROLES.GENERAL,
    ROLES.ODECA,
    ROLES.SOCIETE,
    ROLES.SUPERVISEUR_REGIONAL,
    ROLES.SUPERVISEUR,
  ],
};
